/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

export function Planet({ isReady, onDropComplete, ...props }) {
  const shapeContainer = useRef(null);
  const shperesContainer = useRef(null);
  const ringContainer = useRef(null);
  const { nodes, materials } = useGLTF("/models/Planet.glb");

  // Snap to the "pre-drop" pose immediately, before the loader even
  // finishes, so nothing flashes in its resting pose while the loader's
  // curtain is still revealing the scene underneath.
  useGSAP(() => {
    gsap.set(shapeContainer.current.position, { y: 5 });
    gsap.set(shperesContainer.current.rotation, {
      x: 0,
      y: Math.PI,
      z: -Math.PI,
    });
    gsap.set(ringContainer.current.rotation, { x: 0.8, y: 0, z: 0 });
  }, []);

  useGSAP(
    () => {
      if (!isReady) return;

      // Delayed so the model drops in after the hero title has finished
      // revealing, instead of animating at the same time.
      const tl = gsap.timeline({ delay: 1.4 });
      tl.to(shapeContainer.current.position, {
        y: 0,
        duration: 2.2,
        ease: "circ.out",
        onComplete: () => onDropComplete?.(),
      });
      tl.to(
        shperesContainer.current.rotation,
        {
          x: 0,
          y: 0,
          z: 0,
          duration: 10,
          ease: "power1.inOut",
        },
        "-=25%"
      );
      tl.to(
        ringContainer.current.rotation,
        {
          x: -0.124,
          y: 0.123,
          z: -0.778,
          duration: 10,
          ease: "power1.inOut",
        },
        "<"
      );
    },
    [isReady]
  );

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={shperesContainer}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials["Material.002"]}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={materials["Material.001"]}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      <mesh
        ref={ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials["Material.001"]}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload("/models/Planet.glb");
